# Lotus Per-App Configuration
# 0 = Off, 1 = Uinput (Smooth), 2 = Uinput (Slow), 3 = Uinput (Hardcore), 4 = Surrounding Text, 5 = Preedit, 6 = Emoji Picker
scrcpy=4
kitty=3
org.gimp.GIMP=5
thorium-browser=3
aegisub=5
