color0 #371b24
color1 #fa2455
color2 #ff4d84
color3 #ff5933
color4 #ffbf33
color5 #ff80a7
color6 #ff9780
color7 #f3f2f2
color8 #716267
color9 #fa2455
color10 #ff4d84
color11 #ff5933
color12 #ffbf33
color13 #ff80a7
color14 #ff9780
color15 #f3f2f2

cursor                #f3f2f2
cursor_text_color     #29141b
background            #29141b
foreground            #f3f2f2
selection_foreground  #b6afb1
selection_background  #371b24
active_border_color   #ff4d84
inactive_border_color #371b24
url_color             #ff4d84

active_tab_foreground   #25181c
active_tab_background   #ff4d84
inactive_tab_foreground #b6afb1
inactive_tab_background #371b24
cursor_trail_color      #b6afb1
