color0 #1f2933
color1 #fd4663
color2 #67bde4
color3 #6580e0
color4 #9273da
color5 #93d0ec
color6 #96a7e9
color7 #f2f2f3
color8 #606a6f
color9 #fd4663
color10 #67bde4
color11 #6580e0
color12 #9273da
color13 #93d0ec
color14 #96a7e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #171f26
background            #171f26
foreground            #f2f2f3
selection_foreground  #afb4b6
selection_background  #1f2933
active_border_color   #67bde4
inactive_border_color #1f2933
url_color             #67bde4

active_tab_foreground   #182125
active_tab_background   #67bde4
inactive_tab_foreground #afb4b6
inactive_tab_background #1f2933
cursor_trail_color      #afb4b6
